### ISSUE TITLE
WebView2安装失败

### ISSUE THREAD

**Issue by Wazolm** [MiningCattiva/x-spider#1]
您好，我在安装的时提示安装失败，详细信息里显示无法安装WebView2，exit code是-2147012867。
（我的是Windows7 64位系统exit）
![Installation Aborted](https://github.com/MiningCattiva/x-spider/assets/75199814/fd604591-0c54-4819-b81a-0c06a2f0ac02)

**Comment by MoyuScript** [comment]
WebView2 问题建议去问微软，我也不知道
