### ISSUE TITLE
保存路径模板错误提示

### ISSUE THREAD

**Issue by xzxnc** [MiningCattiva/x-spider#10]
这样写不对吗
\\DSM\Download\推特下载\%USER_NAME%@%USER_ID%

![Snipaste_2024-03-12_16-52-39](https://github.com/MiningCattiva/x-spider/assets/58083110/362a4cad-41c9-4c68-a371-c97756eb0a2e)

**Comment by MoyuScript** [comment]
网络路径没考虑进去，有空的时候看看

**Comment by MoyuScript** [comment]
暂时不打算支持网络路径
