### ISSUE TITLE
下载图片时没有下载原始画质v2

### ISSUE THREAD

**Issue by EXIAFOR** [MiningCattiva/x-spider#11]
你的下载器真的很好用，感谢老哥
注意到url的参数改为了name=4096x4096，按照我自己的经验，其实改为name=orig会好一点
orig获取的是原图，比4096参数好
然后这里给出示例链接，4096的参数只能得到最大4096的图，但是orig可以得到5000的图
orig
[https://pbs.twimg.com/media/FZ1gfpEXEAA8BHa?format=jpg&name=orig](https://pbs.twimg.com/media/FZ1gfpEXEAA8BHa?format=jpg&name=orig)
4096
[https://pbs.twimg.com/media/FZ1gfpEXEAA8BHa?format=jpg&name=4096x4096](https://pbs.twimg.com/media/FZ1gfpEXEAA8BHa?format=jpg&name=4096x4096)
我自己下载测试了，确实还是orig好，希望老哥能修复
参考资料如下
[https://github.com/mikf/gallery-dl/issues/1881](https://github.com/mikf/gallery-dl/issues/1881)

![out](https://github.com/MiningCattiva/x-spider/assets/34876687/940c6550-a271-4e23-8d37-8c43c0645804)

**Comment by EXIAFOR** [comment]
确实离谱，麻烦老哥修改了😵😵

**Comment by MoyuScript** [comment]
可以先在预览版：https://github.com/MiningCattiva/x-spider/releases/tag/v1.1.2-0 试试，issue不用关，之后发布正式版会自动关

**Comment by EXIAFOR** [comment]
看了代码已经修改了，应该问题不大
