### ISSUE TITLE
下载任务里点击打开目录没有打开文件所在文件夹，而是打开此电脑

### ISSUE THREAD

**Issue by tomingqiao** [MiningCattiva/x-spider#12]
我的上一个issue可能表述不清楚，当然也可能就我有这个问题，这次贴上过程截图

版本号：1.1.1

保存文件夹设置：
![Snipaste_2024-03-12_16-09-47](https://github.com/MiningCattiva/x-spider/assets/57249360/e6abd610-37a4-4a7a-86a3-273806419105)

下载管理界面，点击打开目录：
![Snipaste_2024-03-12_16-10-09-2](https://github.com/MiningCattiva/x-spider/assets/57249360/98c9364d-bf30-413d-8d52-c978a110c34d)

出现此电脑，而不是我设置的文件夹路径：
![Snipaste_2024-03-12_16-11-34](https://github.com/MiningCattiva/x-spider/assets/57249360/d96dc326-d1cf-4b9f-b27f-f0aec0a35823)

**Comment by MoyuScript** [comment]
我这一直无法复现。。。

**Comment by tomingqiao** [comment]
> 我这一直无法复现。。。

没事了，我现在用1.1.1又有了，但我更新到2.0.0创建新的下载任务失败😵，但1.1.1的是可以下载的，如图，要开个新的issue吗？
![Snipaste_2024-03-17_19-26-01](https://github.com/MiningCattiva/x-spider/assets/57249360/e58f0175-4638-4c2d-991d-271b689849c7)

**Comment by MoyuScript** [comment]
看看 #24
