### ISSUE TITLE
同一账号同时下载图片和视频时大部分图片报错undefined，视频却能正常下载

### ISSUE THREAD

**Issue by YuanenSuyan** [MiningCattiva/x-spider#16]
目前用的v1.1.0版本
![Snipaste_2024-03-12_23-55-48](https://github.com/MiningCattiva/x-spider/assets/78782958/0f71cbdb-d4de-485c-9521-8a934a60a347)
不过重新下载图片后，没问题了
很奇怪只有图片有这个问题，而且部分图片是可以直接下载的，有点晕

**Comment by MoyuScript** [comment]
先升级最新版试试

**Comment by YuanenSuyan** [comment]
最新版后没有了这个问题，2.0.1版本有新问题了
