### ISSUE TITLE
创建任务的时候可能会失败，然后没有对应的错误记录机制，无法判断文件是否全部被请求下载

### ISSUE THREAD

**Issue by EXIAFOR** [MiningCattiva/x-spider#17]
有大量媒体内容的账号下载的时候可能会报错 >>创建任务失败<<
然后程序好像就不会再进行请求了，这样可能导致一些媒体没有被请求到
触发的条件个人觉得应该是网络波动问题
但是确实挺影响使用的
不一定能复现，但是我这边已经出现过很多次这样的问题了
![Snipaste_2024-03-13_00-56-06](https://github.com/MiningCattiva/x-spider/assets/34876687/7b779fab-77a2-4d1c-919c-bd5c7fbb4ebe)

**Comment by MoyuScript** [comment]
这个需要大变更，对错误进行处理啥的比较麻烦，后续版本再加上

**Comment by MoyuScript** [comment]
暂时使用简单重试机制来解决，后续考虑再完善：https://github.com/MiningCattiva/x-spider/releases/tag/v2.1.2-6
