### ISSUE TITLE
批量下载没有反应，下载任务那里显示有任务，但是发送0，也没有在下载，单个下载视频和图片可以

### ISSUE THREAD

**Issue by shoreson** [MiningCattiva/x-spider#23]
如题，已是最新版

**Comment by MoyuScript** [comment]
可能是有相同文件存在被跳过了，但状态忘记更新了，你检查一下是不是已经下载过了

**Comment by MoyuScript** [comment]
试试：https://github.com/MiningCattiva/x-spider/releases/tag/v2.0.1-0

**Comment by YuanenSuyan** [comment]
还是不行
![Snipaste_2024-03-25_12-32-19](https://github.com/MiningCattiva/x-spider/assets/78782958/1d86c613-d245-4c22-87fa-f1dfd5368727)
