### ISSUE TITLE
安装包点击安装时，无法安装Aria2c.exe

### ISSUE THREAD

**Issue by Pulucaro** [MiningCattiva/x-spider#25]
![{E5EBFA6F-D557-4908-B757-0F2027D6EBE9}](https://github.com/MiningCattiva/x-spider/assets/129641238/caac66ab-d08a-418a-9f86-66543122aefe)

几个安装包都试了下，每次在安装的时候都弹出这个内容，导致无法安装到Aria2c.exe

**Comment by Pulucaro** [comment]
刚重新看了一下，应该是因为第一次删除xspider的时候Aria2c没卸载干净，然后二次安装的时候就覆盖失败了。

**Comment by MoyuScript** [comment]
tauri自带的安装程序，不属于本软件的问题
