### ISSUE TITLE
【建议】推文内容作为文件名变量

### ISSUE THREAD

**Issue by InMirrors** [MiningCattiva/x-spider#26]
**功能描述**

增加文件名变量，使得推文内容可以作为文件名的一部分。

用空格替换推文中的换行符，截断过长的文本。至于多长是过长，可以设定一个固定值，例如 100 字符，超出部分截断；最好能增加一个设置项由用户自行设定，让用户根据自己的命名习惯确定合适的长度。

**背景**

文件名有推文内容的话，浏览图片时可以查看推文内容，在一定程度上实现本地逛推。并且想起某图片或视频时，也可以根据对推文内容的印象，搜索相应的关键字，快速定位文件。

**Comment by MoyuScript** [comment]
Duplicate of #15
