### ISSUE TITLE
搜索结果向下滑动时会白屏

### ISSUE THREAD

**Issue by khvarenah** [MiningCattiva/x-spider#28]
**检查清单**

- [ 是 ] 软件版本是否已升级到最新版。
- [ 是 ] 是否没有重复的 Issue。

**问题描述**

向下滑动时会白屏

**复现步骤**

1. 搜索框搜索用户，向下滑动结果页面
![1](https://github.com/MiningCattiva/x-spider/assets/55649731/868abca4-77e5-494a-84b5-03a17c986fbe)
2. 白屏
 ![2](https://github.com/MiningCattiva/x-spider/assets/55649731/d24ffd37-bf71-4ec4-8ec8-762e16af66d3)

**期望行为**

正常能够滑动到用户的最后一张照片。

**其他信息**

系统为完全新装，安装了必要运行库和python
[DxDiag.txt](https://github.com/MiningCattiva/x-spider/files/14801877/DxDiag.txt)

**Comment by MoyuScript** [comment]
未复现

**Comment by Artanis55** [comment]
我也是结果一多，显示结果时候会白屏
https://github.com/MiningCattiva/x-spider/assets/34433492/c23c8d4a-3e65-431d-8dce-1800b49ab2fe

**Comment by MoyuScript** [comment]
尝试一下：https://github.com/MiningCattiva/x-spider/releases/tag/v2.1.1-0

**Comment by Artanis55** [comment]
> 尝试一下：https://github.com/MiningCattiva/x-spider/releases/tag/v2.1.1-0

测试着不会白屏了，但是这个版本设置变量里面好像无法设置资源的ID、宽度、高度了

**Comment by khvarenah** [comment]
> 尝试一下：https://github.com/MiningCattiva/x-spider/releases/tag/v2.1.1-0

2.1版经过初步尝试未出现之前的白屏情况。
2.0时白屏多发生在结果列表的最末端，继续下滑就会白屏。

**Comment by MoyuScript** [comment]
> > 尝试一下：https://github.com/MiningCattiva/x-spider/releases/tag/v2.1.1-0
> 
> 测试着不会白屏了，但是这个版本设置变量里面好像无法设置资源的ID、宽度、高度了 ![Snipaste_2024-04-15_14-37-56](https://private-user-images.githubusercontent.com/34433492/322376398-3e2a1db8-1d12-43da-9ff0-aa105a09182f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxODA0NTMsIm5iZiI6MTcxMzE4MDE1MywicGF0aCI6Ii8zNDQzMzQ5Mi8zMjIzNzYzOTgtM2UyYTFkYjgtMWQxMi00M2RhLTlmZjAtYWExMDVhMDkxODJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDExMjIzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmOGE1N2JhZTBiMzE0OWVlMjI3MzNmNDM1ZmI3YjQzZGM4YjI0OWY4MzA5NTRmNjMwMjEzZjk0OGExMTBhYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yU-h0KB7tCrkBOJ03bkzmYK-MGHNNDTyTRSHt7G-_V0) ![Snipaste_2024-04-15_14-57-26](https://private-user-images.githubusercontent.com/34433492/322381316-dcd74777-c414-448b-83a6-8fb2fb33a9fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxODA0NTMsIm5iZiI6MTcxMzE4MDE1MywicGF0aCI6Ii8zNDQzMzQ5Mi8zMjIzODEzMTYtZGNkNzQ3NzctYzQxNC00NDhiLTgzYTYtOGZiMmZiMzNhOWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDExMjIzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkZDQyZmQ5MWQxMDAwZTQ2OTVlY2VlMmRkMDJjYmU5MTg3NGQ0ZGU0MjQxOWZiNDkxYjNhNTc5ODI4ZWMyNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x2iF_MDsO-Cmi2XcILqPEnJITUq4MADX1xLBLH4atN0)

追踪 #35
