### ISSUE TITLE
建議下載時創建一個下載用戶id的文件夾

### ISSUE THREAD

**Issue by xiaole3349** [MiningCattiva/x-spider#3]
rt。
把下載的東西都丟進這個文件夾，就和fanboxdownloader的一樣。

**Comment by BennyCodeX** [comment]
复议

**Comment by MoyuScript** [comment]
添加功能：bb3f56841ef730efa79db06c81658aa0f0bc3cd8 50ffc7a190a469d0f6e4f09524461bfa9b73c268
尝试最新预览版

**Comment by MoyuScript** [comment]
https://github.com/MiningCattiva/x-spider/releases/tag/v1.1.0
