### ISSUE TITLE
不论是单张图片还是批量下载均显示“下载失败”

### ISSUE THREAD

**Issue by Pulucaro** [MiningCattiva/x-spider#30]
**检查清单**

- [x] 软件版本是否已升级到最新版。
- [x] 是否没有重复的 Issue。

**问题描述**

安装完v2.0后，按照提示登录账号并设置好端口后搜索作者主页，点击下载图片后提示“下载失败”

**复现步骤**

1. 1-单张图片下载失败提示
![1-单张图片下载失败提示](https://github.com/MiningCattiva/x-spider/assets/129641238/3300e970-ac30-48d1-90d8-c294fca5b58c)
2.2-批量下载失败提示
![2-批量下载失败提示】](https://github.com/MiningCattiva/x-spider/assets/129641238/f4100c5f-561d-48db-835d-285fcdacf20f)
3.3-设置页面
![3-设置页面](https://github.com/MiningCattiva/x-spider/assets/129641238/4eed6fea-b73f-436d-8b9d-3d4a16a26326)

**期望行为**

正常使用软件

**其他信息**

v1版本的时候使用是没问题的，后面更新后就不行了，不过这些设置我都没改过，就很疑惑。

**Comment by MoyuScript** [comment]
把“使用系统代理”关掉试试，填了代理地址就不要开这个开关了

**Comment by Pulucaro** [comment]
关掉后也还是不行...

**Comment by MoyuScript** [comment]
你看看 #31 ，是否是这个问题
