### ISSUE TITLE
关于图片下载失败，是否有可能与aria文件有关系

### ISSUE THREAD

**Issue by YuanenSuyan** [MiningCattiva/x-spider#31]
**检查清单**

- [ √] 软件版本是否已升级到最新版。
- [ √] 是否没有重复的 Issue。

**问题描述**

![image](https://github.com/MiningCattiva/x-spider/assets/78782958/080eb7a4-66d1-4d6c-a99e-508b954cd33c)
![image](https://github.com/MiningCattiva/x-spider/assets/78782958/53b8062a-a33a-40f9-a935-fae6f95de196)
在最近几个版本里下载时均出现了如上图所示的情况，之后图片一直下载失败，是否有所关联

**复现步骤**

1.初始界面，点击左上角开始下载，提示下载成功，但是切换到下载管理界面，下载任务数为0
![image](https://github.com/MiningCattiva/x-spider/assets/78782958/2a78d428-1fc7-41e8-8208-ccebe3baf9e0)
![image](https://github.com/MiningCattiva/x-spider/assets/78782958/a7bcfceb-3452-4b76-bc7e-ac7ca2200a8e)
![image](https://github.com/MiningCattiva/x-spider/assets/78782958/88ceacda-0e69-4138-9c67-157005b04da9)

2.点击单个下载，直接提示下载失败
![image](https://github.com/MiningCattiva/x-spider/assets/78782958/69679a8e-a99c-4fc7-b168-7900d837b04b)
![image](https://github.com/MiningCattiva/x-spider/assets/78782958/8d867e61-e07f-4200-a46f-473378268354)

3.系统设置，代理必须开启，否则无法登录账户或者搜索用户。使用系统代理时，代理地址不能为空？尽管关闭系统代理，图片依旧无法下载，代理地址与代理服务器的地址相同。
![image](https://github.com/MiningCattiva/x-spider/assets/78782958/5397ba82-8632-430b-834b-997f95126a94)
![image](https://github.com/MiningCattiva/x-spider/assets/78782958/d925e3d0-6431-415d-867b-151d7d18e4da)

**期望行为**

我不清楚是否因为aria文件下载失败导致图片无法下载？
**其他信息**

1.如果可以希望能让使用成功的朋友来说明一下系统代理配置的情况
2.是否在下载过程中出现了aria文件报错的情况

**Comment by MoyuScript** [comment]
但aria版本我一直没变动过，我这边也一直是正常，尝试一下手动卸载旧版后再安装，如果还不行的话装下旧版看看那个版本没问题

**Comment by YuanenSuyan** [comment]
老师我试了一下只有1.1.1的版本是没有问题的，就是我第一次安装的版本，其他的1.1.0和1往后的都不太行
![image](https://github.com/MiningCattiva/x-spider/assets/78782958/68c6cd3e-ee59-48eb-ab99-ae2a44156843)
![image](https://github.com/MiningCattiva/x-spider/assets/78782958/95ba5f73-cc97-4931-8607-11e693af3f84)

**Comment by MoyuScript** [comment]
最新版看看在aria目录下使用命令行运行我上面说的命令看看是否正常？

**Comment by YuanenSuyan** [comment]
2.0.0版本输入命令行后显示如下txt，没有报错，软件仍然运行不了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MiningCattiva/x-spider"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月4日(星期四) 晚上8:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MiningCattiva/x-spider] 关于图片下载失败，是否有可能与aria文件有关系 (Issue #31)





 
最新版看看在aria目录下使用命令行运行我上面说的命令看看是否正常？

**Comment by MoyuScript** [comment]
提供一下完整设置页面

**Comment by YuanenSuyan** [comment]
这里是5张设置图，如果我没理解错完整设置的意思


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MiningCattiva/x-spider"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月4日(星期四) 晚上8:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MiningCattiva/x-spider] 关于图片下载失败，是否有可能与aria文件有关系 (Issue #31)





 
提供一下完整设置页面

**Comment by YuanenSuyan** [comment]
![cmd建议](https://github.com/MiningCattiva/x-spider/assets/78782958/c9a98a1d-a2f2-42b9-95fa-779617c9725a)
![cmd界面1](https://github.com/MiningCattiva/x-spider/assets/78782958/9d3046db-c256-4f91-8c46-120c3ceb1d27)
![设置1（系统代理关了也不行）](https://github.com/MiningCattiva/x-spider/assets/78782958/a9df4572-3730-47ee-a4cd-202ccff272aa)
![设置2](https://github.com/MiningCattiva/x-spider/assets/78782958/b9ffbee6-61d0-431f-b11b-ea9d3c132675)
![cmd后连接设置（关闭这里代理后会登不上x-spider）](https://github.com/MiningCattiva/x-spider/assets/78782958/2d180da7-636e-4ebe-a69d-af56952ce910)
不好意思昨天没理解到意思，这是五张图片

**Comment by MoyuScript** [comment]
我这无法复现，等之后看看加个日志系统才能看看是怎么回事

**Comment by YuanenSuyan** [comment]
@XiaoYiyaa 感谢，我重新安装时也不会了。但是用老版本v1.1.1下载图片时出现了如下图按钮卡死的情况（没有正确或错误的提示），使用v2.0.0版本的时候则是报错，均不能正常下载图片了。这下真不懂了hhh
![image](https://github.com/MiningCattiva/x-spider/assets/78782958/cf1857de-2a6b-4b32-bae4-7bb501c1eed3)

刚刚更新了v2.1.0版本，我不知道我电脑有什么问题，还是下载不了
![image](https://github.com/MiningCattiva/x-spider/assets/78782958/7c7604d4-7a73-4974-8cdd-bc1d5377cb34)

**Comment by MoyuScript** [comment]
可能是文件夹模板的问题，试试随便输入一点再删干净
