### ISSUE TITLE
任务创建之后已发送为0

### ISSUE THREAD

**Issue by zhonghong78** [MiningCattiva/x-spider#33]
**检查清单**

- [ √] 软件版本是否已升级到最新版。
- [ √] 是否没有重复的 Issue。

**问题描述**

当我生成一个任务之后，已发送为0
**复现步骤**

1. 
![image](https://github.com/MiningCattiva/x-spider/assets/60834932/37423f2f-795a-412f-bc9a-e667ef31e36b)
2.
![image](https://github.com/MiningCattiva/x-spider/assets/60834932/6a61f353-8de1-4f8d-a398-f71de3aa2ee9)
3.
![image](https://github.com/MiningCattiva/x-spider/assets/60834932/1cad2347-971b-4d65-bf9e-0a996c5af571)

**期望行为**

**其他信息**

**Comment by zhost001** [comment]
我用最新版也这样了,没法下载了

**Comment by zhonghong78** [comment]
@InMirrors 好像是这样，把%CONTENT% 这个标签放开确实可以下。
但是就想问问作者大大是什么原因，是CONTENT超长，还是因为里面有特殊字符，在输出的时候卡住，可不可以解决

**Comment by zhost001** [comment]
根据我的测试,和标签没关系，我重启软件，重启电脑和网络都不行，是某些x的原因，我今天下别的x好好的，我又去测试卡住的x,我下载cdooys1这个x到一定数量就卡住，然后软件就什么不正常了，其他的x就已发送变成0没法下了

**Comment by eqqssbbqbb** [comment]
我用的时候也有类似的问题，某些用户的明明查到还有几百个媒体没下，而且大多是比较久以前的（大概在2017~2022年的左右），一点下载就直接下载完毕，仿佛是根本没检测到有文件一样，但是软件明明识别出来了（用下载好的文件数目和主页检测到的媒体数目对比出来的，且经过浏览器上X验证，确实是缺），有一些用户的就没有这种问题（即便是2017年左右），不知能修么

**Comment by MoyuScript** [comment]
尝试一下：https://github.com/MiningCattiva/x-spider/releases/tag/v2.1.1-0

**Comment by zhonghong78** [comment]
> 尝试一下：https://github.com/MiningCattiva/x-spider/releases/tag/v2.1.1-0

尝试了一下，这个版本任务下载不了东西
![image](https://github.com/MiningCattiva/x-spider/assets/60834932/702f3754-9e37-41c4-bcef-1dfb7fde2677)

**Comment by MoyuScript** [comment]
无法复现，重启电脑后再试试

**Comment by MoyuScript** [comment]
尝试一下：https://github.com/MiningCattiva/x-spider/releases/tag/v2.1.2-1  看有没有解决，没有的话上传一下日志

**Comment by zhonghong78** [comment]
> 尝试一下：https://github.com/MiningCattiva/x-spider/releases/tag/v2.1.2-1 看有没有解决，没有的话上传一下日志

可以了，作者大大

**Comment by KIZUNASORA** [comment]
> 尝试一下：https://github.com/MiningCattiva/x-spider/releases/tag/v2.1.2-1 看有没有解决，没有的话上传一下日志

这个版本还是没办法全部下载，一直显示共1个任务创建中
[2024-04-16 012908.log](https://github.com/MiningCattiva/x-spider/files/14982538/2024-04-16.012908.log)
[2024-04-16 012944.log](https://github.com/MiningCattiva/x-spider/files/14982539/2024-04-16.012944.log)
[2024-04-16 013109.log](https://github.com/MiningCattiva/x-spider/files/14982540/2024-04-16.013109.log)

**Comment by MoyuScript** [comment]
新增了请求重试机制，现在应该会比之前稳定一些了：https://github.com/MiningCattiva/x-spider/releases/tag/v2.1.2-2

**Comment by MoyuScript** [comment]
> 试了一下[2.1.2-2](https://github.com/MiningCattiva/x-spider/releases/tag/v2.1.2-2)，推文长度设置为80时还是在差不多的地方卡住，停止发送。要是这个问题难修复的话，加个“推文内容太长可能导致爬取失败”的提示算了。就我下载的几个账号而言，设置为50时没问题，50字也能大概知道推文要说什么了。

日志发一下

**Comment by MoyuScript** [comment]
https://github.com/MiningCattiva/x-spider/actions/runs/8709282485

等发完可以再试一下

**Comment by KIZUNASORA** [comment]
> 新增了请求重试机制，现在应该会比之前稳定一些了：https://github.com/MiningCattiva/x-spider/releases/tag/v2.1.2-2

v2.1.2-2版本终于能在我的电脑上正常下载使用了！！好激动，很快速很赞的软件！就是每次下载的时候都会弹出来这个弹窗请问提示是什么意思呢？（好像这个弹窗并不会影响到下载）
![Uploading 7c8c49b84720391d6bb43e3a07509858.png…]()

**Comment by KIZUNASORA** [comment]
会显示这样的弹窗：爬虫任务运行失败：TypeError：Cannot read properties of undefined（reading'createdAt'）
![7c8c49b84720391d6bb43e3a07509858](https://github.com/MiningCattiva/x-spider/assets/167122593/9a89b124-b71a-4693-a19b-2d60ba4ba667)

**Comment by MoyuScript** [comment]
> 会显示这样的弹窗：爬虫任务运行失败：TypeError：Cannot read properties of undefined（reading'createdAt'） ![7c8c49b84720391d6bb43e3a07509858](https://private-user-images.githubusercontent.com/167122593/323016173-9a89b124-b71a-4693-a19b-2d60ba4ba667.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMTQyNjksIm5iZiI6MTcxMzMxMzk2OSwicGF0aCI6Ii8xNjcxMjI1OTMvMzIzMDE2MTczLTlhODliMTI0LWI3MWEtNDY5My1hMTliLTJkNjBiYTRiYTY2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QwMDMyNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjBhOTljZjk0ZDc3ZDY2NDk2ZDhjZjRlYTBiMjU5ZDhiNDViM2RjYjA3YzEwNTUyYmExNGI4ZDMzMTM3MGViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PEMR6FQlNB6V7Abb4J9rHj3az5c4L6bYInABi2P5pP8)

上传日志
