### ISSUE TITLE
【嚴重BUG反饋】關於安裝與卸載

### ISSUE THREAD

**Issue by xiaole3349** [MiningCattiva/x-spider#34]
**检查清单**

- [x] 是否没有重复的 Issue。
- [x] 软件版本是否已升级到最新版。

**问题描述**

安裝時，如果用戶自己選擇了路徑，軟件安裝程序并不會創建新的文件夾將X-spider的文件放入文件夾内。
導致的後果就是如果用戶把軟件安裝在Program File時，軟件的卸載程序會將Program File中的所有文件識別爲X-spider的文件。
恭喜，完美還原了少女前綫2的BUG。
**复现步骤**

1. 安裝軟件時將軟件安裝目錄改成Program File。
3. 卸載軟件。

**期望行为**

重寫你的安裝程序或者卸載程序

**其他信息**

不建議嘗試這個bug，我Program File文件内的東西差點被刪乾净了。

**Comment by xiaole3349** [comment]
> **检查清单**
> 
>     * [x]  软件版本是否已升级到最新版。
> 
>     * [x]  是否没有重复的 Issue。
> 
> 
> **问题描述**
> 
> 安裝時，如果用戶自己選擇了路徑，軟件安裝程序并不會創建新的文件夾將X-spider的文件放入文件夾内。 導致的後果就是如果用戶把軟件安裝在Program File時，軟件的卸載程序會將Program File中的所有文件識別爲

**Comment by MoyuScript** [comment]
这个问题去给tauri官方反馈

**Comment by xiaole3349** [comment]
> 这个问题去给tauri官方反馈

嘗試安裝並卸載了其他打包成windows安裝程序的tauri應用，并沒有復現此問題。
只有X-spider出現了這個問題。
