### ISSUE TITLE
因为无法下载到更早的图片，导致的实际下载数量和推特上显示的媒体数量不符

### ISSUE THREAD

**Issue by KIZUNASORA** [MiningCattiva/x-spider#37]
**检查清单**

- [√] 软件版本是否已升级到最新版。
- [√] 是否没有重复的 Issue。

**问题描述**

可能是因为无法下载到更早的图片，导致的实际下载数量和推特上显示的媒体数量不符
**复现步骤**

1. 以日下氏(ゆっきー)@yukkieeeeeen老师的显示为5057 张照片和视频为例，进行下载
![Snipaste_2024-04-17_07-13-48](https://github.com/MiningCattiva/x-spider/assets/167122593/d5b6e339-dcee-4f2b-bbdf-a8b7c1230618)
2. 下载后只下载了1029个文件，最早停在了2021年六18日
![Snipaste_2024-04-17_07-14-34](https://github.com/MiningCattiva/x-spider/assets/167122593/ced8a458-386d-4750-8cb5-de51afc0669d)

3. 将时间日期日期范围设置为2016-10-01到2021-06-18进行下载，在共1个任务创建中只会出现【已跳过】而不会进行下载
![64ec804b8b3d3d81eb9e9aec2efbd51c](https://github.com/MiningCattiva/x-spider/assets/167122593/1738c504-375e-4261-a6ee-d74bf6510baa)
![768d69133f0c34135a009132ebf42cd4](https://github.com/MiningCattiva/x-spider/assets/167122593/e03c0f52-5d62-45ca-8f50-3345ef612343)

**期望行为**

希望能在后续更新中支持更早的图片下载，如果能做到和之前某已经不能用的浏览器插件一样可以下载改账号下所有图片就完美了！

**其他信息**

**Comment by MoyuScript** [comment]
已跳过是因为还没爬到对应日期，下不全是因为推特 API 限制，目前还不知道有什么解决方案

**Comment by MoyuScript** [comment]
可以试试：https://github.com/MiningCattiva/x-spider/actions/runs/8724603918
