### ISSUE TITLE
主页加载问题

### ISSUE THREAD

**Issue by WesterlyGraph68** [MiningCattiva/x-spider#38]
**检查清单**

- [ 是] 软件版本是否已升级到最新版。
- [是 ] 是否没有重复的 Issue。

**问题描述**

登陆之后，有些账号的图片是可以正常下载的，但是我目前发现两个账号有无法加载完毕的情况，它的表现状况为后面的未加载内容突然出现但像是被某种不可抗拒的因素导致这些内容加载了1帧的情况下瞬间消失，之后软件就反反复复卡着，而且只能下载已加载的图片
**复现步骤**

1.
![屏幕截图 2024-04-18 185558](https://github.com/MiningCattiva/x-spider/assets/125789295/cdb97037-b403-4c82-b0c1-29b5e944b666)
2.就是一直在转圈，加载了但没有完全加载

**期望行为**

希望图片可以正常加载且下载
**运行日志**

[2024-04-18 185822.log](https://github.com/MiningCattiva/x-spider/files/15023777/2024-04-18.185822.log)
**其他信息**

**Comment by MoyuScript** [comment]
发完试试：https://github.com/MiningCattiva/x-spider/actions/runs/8740666829
