### ISSUE TITLE
软件错误问题

### ISSUE THREAD

**Issue by WesterlyGraph68** [MiningCattiva/x-spider#39]
**检查清单**

- [是] 软件版本是否已升级到最新版。
- [是 ] 是否没有重复的 Issue。

**问题描述**

1.主页加载问题已解决，刚开始程序运行一切正常，但是当我第一次使用该软件最新测试版（[v2.2.1-0]）下载第一个用户推文媒体时（共300多个媒体）一切正常，下载完毕，但我开始下载第二个用户推文媒体时（共1000多个媒体），大概下到在900多媒体时，软件提示爬虫提取失败，且关掉软件后，再次打开软件，再次在主页界面搜索用户主业时软件就一直显示正在加载图片且软件无法点击其他按钮，只能关闭软件，且重启电脑也无济于事
**复现步骤**

1.![屏幕截图 2024-04-19 094624](https://github.com/MiningCattiva/x-spider/assets/125789295/b7aea4b7-2b5f-41f0-a1ba-f4bce23c5aff)

**期望行为**

软件课正常下载图片
**运行日志**

[2024-04-19 094651.log](https://github.com/MiningCattiva/x-spider/files/15032153/2024-04-19.094651.log)

**其他信息**

**Comment by MoyuScript** [comment]
日志内容过少，请补充完整日志
