### ISSUE TITLE
下载时显示“目标主要名称不正确”导致下载失败

### ISSUE THREAD

**Issue by Justinsu123** [MiningCattiva/x-spider#41]
下载时显示“目标主要名称不正确”导致下载失败
![1713500390118](https://github.com/MiningCattiva/x-spider/assets/167500129/54ca02eb-392a-492a-9a96-1eaeb7acfe1c)

**Comment by Justinsu123** [comment]
![1713501084656](https://github.com/MiningCattiva/x-spider/assets/167500129/73675b4d-e4fc-47fb-9e42-97993b2679f3)
现在又变成了操作成功完成（0），可是没有下载成功

**Comment by MoyuScript** [comment]
按模板提问
