### ISSUE TITLE
新增的抓取方式抓取结果空白

### ISSUE THREAD

**Issue by chromacle** [MiningCattiva/x-spider#43]
**检查清单**

- [√ ] 软件版本是否已升级到最新版。
- [√ ] 是否没有重复的 Issue。

**问题描述**

感谢大佬新增了抓取方式。可是多次试验，发现好像抓取无效。实际抓取日期范围内有媒体，但抓取结果都是空白。

**复现步骤**

例如抓取推主 sakamoto_AHR 的媒体
普通抓取方式只能抓取到2017年12月的媒体。就想通过新增的 帖子 方式抓取更早日期的内容，设置2017-09-01到2017-11-01 尝试抓取（通过高级搜索search-advanced可以看到实际存在媒体），虽然有“任务下载完成”的提示，但是实际抓取不到任何媒体。
![Screenshot 2024-04-21 173942](https://github.com/MiningCattiva/x-spider/assets/163319403/fff841e3-9fba-411d-8ca9-43e85411dec2)
![Screenshot 2024-04-21 174110](https://github.com/MiningCattiva/x-spider/assets/163319403/5be8a2e6-3cb3-4b9e-ae88-50af8c97583e)

**Comment by MoyuScript** [comment]
关注：https://github.com/MiningCattiva/x-spider/actions/runs/9139341572
