### ISSUE TITLE
twitter升级了域名，现版本登录异常

### ISSUE THREAD

**Issue by Naielc** [MiningCattiva/x-spider#49]
**检查清单**

- [ x ] 软件版本是否已升级到最新版。
- [ x ] 是否没有重复的 Issue。

**问题描述**

twitter升级了域名，现版本登录异常

**Comment by MoyuScript** [comment]
关注：https://github.com/MiningCattiva/x-spider/actions/runs/9136486252

**Comment by ryouu2023** [comment]
> 关注：https://github.com/MiningCattiva/x-spider/actions/runs/9136486252

怎么修改推特域名呢

**Comment by windowshome** [comment]
能登录了，但是搜索用户id 不返回结果
