### ISSUE TITLE
发现两个问题

### ISSUE THREAD

**Issue by tomingqiao** [MiningCattiva/x-spider#5]
1.下载图片时没有下载原始画质(或者说可以添加一个改变下载图片画质的功能)。

2.图片下载完打开文件目录(我改成d盘下的一个文件夹)时，直接打开的是此电脑。

**Comment by MoyuScript** [comment]
1. bb6d004df490ab17f14c484b344c78b346816c9d （[V1.1.0](https://github.com/MiningCattiva/x-spider/releases/tag/v1.1.0)）
2. 未复现
