### ISSUE TITLE
使用中报错下载任务失败和爬虫运行失败

### ISSUE THREAD

**Issue by iamshy520** [MiningCattiva/x-spider#51]
**检查清单**

- [x] 软件版本是否已升级到最新版。
- [x] 是否没有重复的 Issue。

**问题描述**

1、下载单个文件报错如下
创建下载任务失败：Aria2 调用 aria2.addUri 失败：Unauthorized
2、批量下载报错如下
爬虫任务运行失败：Cannot read properties of undefined (reading 'status')

**复现步骤**

1.
![image](https://github.com/MiningCattiva/x-spider/assets/42052567/0a2d14d9-2292-47b1-ad18-58b4d134453d)
2.
![image](https://github.com/MiningCattiva/x-spider/assets/42052567/fefd35d4-03b1-460f-8831-1ff0dbbac5fa)

**运行日志**

[2024-05-20 103016.log](https://github.com/MiningCattiva/x-spider/files/15372078/2024-05-20.103016.log)

**其他信息**

版本为2.2.2

**Comment by MoyuScript** [comment]
重启电脑

**Comment by iamshy520** [comment]
问题解决了，非常感谢，请您喝瓶水。
