### ISSUE TITLE
远程主机强迫关闭了一个现有的连接

### ISSUE THREAD

**Issue by Getsumei-L** [MiningCattiva/x-spider#55]
**检查清单**
- [✓] 软件版本是否已升级到最新版。
- [✓] 是否没有重复的 Issue。

**问题描述**
软件无法加载图片，下载时报错。
2024-05-24 17-33-02 GirlsFrontline 1793938246625595409-1.png SSL/TLS handshake failure: Error: 远程主机强迫关闭了一个现有的连接。 (2746)

**复现步骤**
1.![1](https://github.com/MiningCattiva/x-spider/assets/79787706/adfcd8ec-aed4-43e2-a960-4765cef57774)
2.![2](https://github.com/MiningCattiva/x-spider/assets/79787706/b1b129bf-ad09-4b64-b030-e1bfe6ff90b4)
3.![3](https://github.com/MiningCattiva/x-spider/assets/79787706/f52fdbd5-d608-4caa-a53c-0b0207a75385)

**期望行为**
正常下载

麻烦作者大大帮忙看下

**Comment by Getsumei-L** [comment]
好像换了个协议就可以用了( ꒪Д꒪)ノ

**Comment by SunRelease** [comment]
> **检查清单**
> 
> * [✓] 软件版本是否已升级到最新版。
> * [✓] 是否没有重复的 Issue。
> 
> **问题描述** 软件无法加载图片，下载时报错。 2024-05-24 17-33-02 GirlsFrontline 1793938246625595409-1.png SSL/TLS handshake failure: Error: 远程主机强迫关闭了一个现有的连接。 (2746)
> 
> **复现步骤** 1.![1](https://private-user-images.githubusercontent.com/79787706/333576761-adfcd8ec-aed4-43e2-a960-4765cef57774.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5ODI3MzIsIm5iZiI6MTcxNjk4MjQzMiwicGF0aCI6Ii83OTc4NzcwNi8zMzM1NzY3NjEtYWRmY2Q4ZWMtYWVkNC00M2UyLWE5NjAtNDc2NWNlZjU3Nzc0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDExMzM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NDdhMmYxNzJhMzhjMmYwNmJkYzg2YTUxZTRiNDczNzZmNDU1YzU1NzE4ZGVkMDY2YjFkMmE0N2E1NWIxYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mZMRzcFJb-fSHBjCyt80wMuZLQTaPGSWbGYAvnGCdYs) 2.![2](https://private-user-images.githubusercontent.com/79787706/333576771-b1b129bf-ad09-4b64-b030-e1bfe6ff90b4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5ODI3MzIsIm5iZiI6MTcxNjk4MjQzMiwicGF0aCI6Ii83OTc4NzcwNi8zMzM1NzY3NzEtYjFiMTI5YmYtYWQwOS00YjY0LWIwMzAtZTFiZmU2ZmY5MGI0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDExMzM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmMWQ3YTEwZGU2NzQ0M2ViOWI0OGU1NjdiNDQ0NjU4MGMyM2FhNmJkZDU0MjQwZGNjMjNjYmQ5ZjBmMGQ1MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.drtciHYYu2OcVloLR6HImUO1ZhMqJriuOrp7CG7OCKY) 3.![3](https://private-user-images.githubusercontent.com/79787706/333576774-f52fdbd5-d608-4caa-a53c-0b0207a75385.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5ODI3MzIsIm5iZiI6MTcxNjk4MjQzMiwicGF0aCI6Ii83OTc4NzcwNi8zMzM1NzY3NzQtZjUyZmRiZDUtZDYwOC00Y2FhLWE1M2MtMGIwMjA3YTc1Mzg1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDExMzM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkZTYzMDRkZjE3ZWQxOWU1NzFjNjZkNjcyYmQxYmNmNDUwMmRkZmY5ZDc2ZWJlNGI2M2IzMTE5NWMzMjI2ZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dhXRcCv8ZmkSXgEbjcBLj7CH_TdVlQ9phIXzbLBHIQw)
> 
> **期望行为** 正常下载
> 
> 麻烦作者大大帮忙看下

老兄，如果你这个能下载完4900多个媒体文件吗，我有个想爬的账号下再到700多就停止了，不能全部下载所有媒体

**Comment by NyoronGero** [comment]
我爬了几十个就被马斯克限制了，网页都看不到该账号【帖子】栏的推😔

**Comment by Getsumei-L** [comment]
> > **检查清单**
> > 
> > * [✓] 软件版本是否已升级到最新版。
> > * [✓] 是否没有重复的 Issue。
> > 
> > **问题描述** 软件无法加载图片，下载时报错。 2024-05-24 17-33-02 GirlsFrontline 1793938246625595409-1.png SSL/TLS handshake failure: Error: 远程主机强迫关闭了一个现有的连接。 (2746)
> > **复现步骤** 1.![1](https://private-user-images.githubusercontent.com/79787706/333576761-adfcd8ec-aed4-43e2-a960-4765cef57774.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5ODI3MzIsIm5iZiI6MTcxNjk4MjQzMiwicGF0aCI6Ii83OTc4NzcwNi8zMzM1NzY3NjEtYWRmY2Q4ZWMtYWVkNC00M2UyLWE5NjAtNDc2NWNlZjU3Nzc0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDExMzM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NDdhMmYxNzJhMzhjMmYwNmJkYzg2YTUxZTRiNDczNzZmNDU1YzU1NzE4ZGVkMDY2YjFkMmE0N2E1NWIxYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mZMRzcFJb-fSHBjCyt80wMuZLQTaPGSWbGYAvnGCdYs) 2.![2](https://private-user-images.githubusercontent.com/79787706/333576771-b1b129bf-ad09-4b64-b030-e1bfe6ff90b4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5ODI3MzIsIm5iZiI6MTcxNjk4MjQzMiwicGF0aCI6Ii83OTc4NzcwNi8zMzM1NzY3NzEtYjFiMTI5YmYtYWQwOS00YjY0LWIwMzAtZTFiZmU2ZmY5MGI0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDExMzM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmMWQ3YTEwZGU2NzQ0M2ViOWI0OGU1NjdiNDQ0NjU4MGMyM2FhNmJkZDU0MjQwZGNjMjNjYmQ5ZjBmMGQ1MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.drtciHYYu2OcVloLR6HImUO1ZhMqJriuOrp7CG7OCKY) 3.![3](https://private-user-images.githubusercontent.com/79787706/333576774-f52fdbd5-d608-4caa-a53c-0b0207a75385.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5ODI3MzIsIm5iZiI6MTcxNjk4MjQzMiwicGF0aCI6Ii83OTc4NzcwNi8zMzM1NzY3NzQtZjUyZmRiZDUtZDYwOC00Y2FhLWE1M2MtMGIwMjA3YTc1Mzg1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDExMzM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkZTYzMDRkZjE3ZWQxOWU1NzFjNjZkNjcyYmQxYmNmNDUwMmRkZmY5ZDc2ZWJlNGI2M2IzMTE5NWMzMjI2ZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dhXRcCv8ZmkSXgEbjcBLj7CH_TdVlQ9phIXzbLBHIQw)
> > **期望行为** 正常下载
> > 麻烦作者大大帮忙看下
> 
> 老兄，如果你这个能下载完4900多个媒体文件吗，我有个想爬的账号下再到700多就停止了，不能全部下载所有媒体

我随便选了个，我连下都下不了orz

**Comment by MoyuScript** [comment]
上传一下运行日志

**Comment by Getsumei-L** [comment]
> 上传一下运行日志

[2024-06-10 225505.log](https://github.com/user-attachments/files/15775219/2024-06-10.225505.log)

**Comment by MoyuScript** [comment]
这个属于网络问题，检查一下代理有没有效，换线路多试试

**Comment by Getsumei-L** [comment]
> 这个属于网络问题，检查一下代理有没有效，换线路多试试

看了下aria2下载时没有走代理，这个是要在您的软件里设置还是在魔法里面设置
