### ISSUE TITLE
增加赞、转发、浏览量作为变量

### ISSUE THREAD

**Issue by InMirrors** [MiningCattiva/x-spider#58]
**功能描述**

增加这几个变量，用于文件名模版。

**背景**

大部分账号都会有一些没什么意思的图，下载完后要手动检查一遍，删除这些图。这些图的赞、转发、浏览量都很低，如果能支持将这些数据加入文件名的话，可以直接删掉数值低的图，减少工作量。或者不想保存太多图时，可以只保留数值比较高的图。

因为这几项数据的相关性很大，所以支持其中之一就能实现上述用途了。

**Comment by MoyuScript** [comment]
这些值会频繁变化，不支持
