### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by lzr52o** [MiningCattiva/x-spider#6]
Edge找到 应用程序 Cookie展开 里边有个auth_multi的没有token试了一下无法登陆，求大佬怎么解决

**Comment by lzr52o** [comment]
要先打开开发者工具才行，搞定了

**Comment by Jaime0108** [comment]
![屏幕截图_5-6-2024_144236_tauri localhost](https://github.com/MiningCattiva/x-spider/assets/44396107/2d1afcc5-c22a-44f6-954c-18a6b8baf8ec)
为什么我还是登录不了
